SHOW TIMEZONE

SELECT now()

CREATE TABLE timeZ (ts TIMESTAMP WITHOUT TIME ZONE, tsz TIMESTAMP WITH TIME ZONE)

INSERT INTO timeZ VALUES('2000-01-10 10:01:01', '2000-01-10 10:01:01+06')

SELECT * FROM timeZ

SELECT now()

SELECT CURRENT_DATE

SELECT now()::TIME

SELECT now()::DATE

SELECT to_char(now(), 'yyyy/mm/dd')

SELECT CURRENT_DATE - INTERVAL '1 year 2 month'

SELECT age(CURRENT_DATE, '1998/04/02')

SELECT *, age(CURRENT_DATE, dob) FROM students

SELECT extract(YEAR FROM '2000-01-01'::DATE)

SELECT 1::BOOLEAN

SELECT 0::BOOLEAN